# server/Dockerfile

FROM node:18-alpine

RUN apk add --no-cache make gcc g++ python3

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]
